version: 2

project_name: minsig

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: minsig
    main: ./cmd/minsig
    binary: minsig
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: codysoyland
    name: minsig
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## minsig {{ .Tag }}
    
    **Note**: This is an experimental tool and not ready for production use.


kos:
  - id: minsig
    build: minsig
    base_image: gcr.io/distroless/static-debian12
    repositories:
      - ghcr.io/codysoyland/minsig
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "latest"
    bare: true
    preserve_import_paths: false
    sbom: spdx
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.source: "https://github.com/codysoyland/minsig"

